#!/usr/bin/env python3
"""Consolidate, audit, and irreversibly freeze the 80-case ground truth.

This script is intentionally separate from blind-input generation and model
execution.  It refuses to overwrite an existing freeze unless explicitly
asked, so the filesystem timestamp and hashes establish the experiment order.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import subprocess
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path


HERE = Path(__file__).resolve()
ROOT = HERE.parents[1]
WORKSPACE = ROOT.parent
PROJECT_ROOT = WORKSPACE / "FSE2026-harness-degradation" / "sources" / "projects"
DATA = ROOT / "data"
GROUND = ROOT / "ground-truth"
FROZEN = ROOT / "frozen-ground-truth"
RAW = ROOT / "raw-evidence"
SEED = 20260910


SILENT: dict[str, tuple[str, str, str, str, str, str]] = {
    # positive_type, harness_id, inadequacy, H0 state, H1 state, primary evidence
    "N185": ("VP3", "fuzz/c/fuzzlib/fuzzlib.cc", "New io_buffer reader/writer public helpers are not exposed by H0.", "manual io_buffer construction; new helpers uncalled", "calls reader/writer helpers", "dynamic changed-line coverage 0/20 -> 20/20"),
    "N202": ("VP4", "fuzz/c/std/gif_fuzzer.c", "New image_config work-buffer requirement is not queried by H0.", "passes empty work buffer without querying required size", "queries work_buffer_size and allocates it", "historical API-use diff plus three-way run"),
    "N206": ("VP3", "fuzz/c/std/gif_fuzzer.c", "New malloc_slice_u8 public helper is not exposed by H0.", "manual malloc/slice construction", "calls malloc_slice_u8", "dynamic changed-line coverage 0/6 -> 5/6"),
    "N207": ("VP2", "fuzz/c/std/gif_fuzzer.c", "Implemented decoder workbuf_len path is barely exercised by H0.", "retains parallel image_config-derived sizing", "calls decoder workbuf_len", "dynamic changed-line coverage 1/4 -> 4/4"),
    "N215": ("VP5", "fuzz/c/std/gif_fuzzer.c", "Commit changes dirty-rectangle invariant but H0 has no oracle for it.", "does not inspect frame_dirty_rect", "asserts dirty rect containment in frame rect", "dynamic changed-line coverage 2/6 -> 6/6 plus oracle diff"),
    "N216": ("VP5", "fuzz/c/std/gif_fuzzer.c", "Commit changes truncated-input dirty-rect behavior; H0 observes status only.", "does not validate dirty rect on short-read status", "checks dirty-rect invariant before accepting status", "historical oracle placement and three-way run"),
    "N223": ("VP3", "fuzz/c/std/json_fuzzer.c", "New JSON decoder entry has no fuzz target in the H0 portfolio.", "pre-existing portfolio has no JSON target", "new JSON target builds and invokes decoder", "portfolio S0/H0 and S1/H0 PASS; JSON S1/H1 PASS"),
    "N228": ("VP4", "fuzz/c/std/json_fuzzer.c", "Extended token values introduce signed semantics not generated by H0.", "treats token extension value as uint64", "uses int64 and therefore includes negative values", "historical type/config diff plus three-way run"),
    "N231": ("VP3", "fuzz/c/std/cbor_fuzzer.c", "New CBOR decoder entry has no target in H0.", "JSON target only; no CBOR decoding entry", "adds and invokes CBOR target", "three-way portfolio/target build and run"),
    "N233": ("VP4", "fuzz/c/std/json_fuzzer.c", "New trailing-comment quirk cannot be enabled by H0's fixed quirk set.", "new quirk never configured", "adds new quirk to fuzz-controlled mask", "dynamic changed-line coverage 2/24 -> 15/24"),
    "N234": ("VP4", "fuzz/c/std/json_fuzzer.c", "Trailing-comment/newline quirks become incompatible but H0 aliases and combines them.", "old bit mapping can enable invalid combination", "separates new quirk mapping and avoids invalid combination", "configuration diff; coverage is non-monotonic and not used as recovery evidence"),
    "N237": ("VP3", "fuzz/c/std/pixel_swizzler_fuzzer.c", "New rotate-right public helper is not exposed by H0.", "does not call rotate-right", "uses rotate-right when decoding fuzz controls", "dynamic changed-line coverage 0/3 -> 3/3"),
    "N244": ("VP4", "fuzz/c/std/pixel_swizzler_fuzzer.c", "New YA_NONPREMUL pixel format is absent from H0's format selector.", "selector cannot choose new format", "adds format to fuzz-controlled source formats", "dynamic changed-line coverage 0/250 -> 17/250"),
    "N248": ("VP4", "fuzz/c/std/pixel_swizzler_fuzzer.c", "New Y_16LE swizzle source format is absent from H0's selector.", "selector cannot choose Y_16LE", "adds Y_16LE to source formats", "dynamic changed-line coverage 0/93 -> 59/93"),
    "N249": ("VP4", "fuzz/c/std/pixel_swizzler_fuzzer.c", "New BGRA_PREMUL_4X16LE paths are not selectable in H0.", "selector omits new 4x16 format", "adds new format to fuzz-controlled selector", "dynamic changed-line coverage 6/463 -> 121/463"),
    "N250": ("VP4", "fuzz/c/std/pixel_swizzler_fuzzer.c", "ycc_upsampling changes from boolean to model byte; H0 still supplies 1.", "legacy true maps to 0x01 and cannot request 0x80 model", "maps fuzz flag to 0x80 semantic value", "historical argument mapping diff plus three-way run"),
    "N071": ("VP4", "test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp", "Commit adds per-compilation Yul string-repository reset; H0 never resets per fuzz iteration.", "two iterations allocate repository IDs 1 then 2", "resets each iteration; IDs are 1 then 1", "real YulString.h component probe"),
    "N116": ("VP4", "test/tools/fuzzer_common.cpp", "Paris is supported by production but absent from H0's fuzz version vector.", "version vector excludes Paris", "version vector includes Paris", "real EVMVersion.h probe: target 0 -> 1"),
    "N128": ("VP3", "test/tools/ossfuzz/strictasm_diff_ossfuzz.cpp", "New optimizer-sequence cleaning entry and independent sequence mode are not exposed by H0.", "legacy combined program/size-derived sequence path only", "sequence mode calls removeInvalidCharacters", "real OptimiserSettings.h probe and coverage 0/8 -> 8/8"),
    "N132": ("VP4", "test/tools/fuzzer_common.cpp", "Prague is supported by production but absent from H0's fuzz version vector.", "version vector excludes Prague", "version vector includes Prague", "real EVMVersion.h probe: target 0 -> 1"),
}

EXPLICIT = ["N182", "N184", "N186", "N188", "N198", "N201", "N203", "N218", "N226", "N240"]

COEV_NEG: dict[str, tuple[str, str]] = {
    "N193": ("N6", "The new error return is already satisfied by H0's exact-sized allocation; API behavior remains exercised."),
    "N199": ("N1", "Spelling-only production and harness edits introduce no testing requirement."),
    "N209": ("N1", "A local variable rename preserves source behavior and harness scope."),
    "N211": ("N1", "Comment separators only; no executable behavior or harness requirement changes."),
    "N212": ("N1", "Generated constant macros alias the same values and H0 remains valid."),
    "N222": ("N1", "Function-signature formatting only; declarations and calls are semantically unchanged."),
    "N225": ("N1", "Constant rename is applied consistently and changes no input/state requirement."),
    "N235": ("N6", "The prior checksum quirk API remains compatible and H0 reaches the same behavior."),
    "N236": ("N1", "Terminology-only edits introduce no executable testing requirement."),
    "N238": ("N1", "C loop-variable scope cleanup preserves behavior and reachability."),
    "N241": ("N6", "Removing an internal LZW dependency leaves H0's GIF decoder entry and protocol sufficient."),
    "N242": ("N1", "License-text-only change; no executable source or harness semantics change."),
    "N243": ("N1", "SPDX-header-only change; no executable source or harness semantics change."),
    "N005": ("N5", "Removed CBC feature code disappears under the same configuration; no remaining H0 requirement."),
    "N023": ("N1", "Clang warning/prototype formatting changes no runtime harness behavior."),
    "N025": ("N1", "Removal of an unused private-field-access define changes no fuzz target behavior."),
    "N026": ("N1", "Blank/comment cruft removal changes no executable harness behavior."),
}

KNOWN_EXCLUSIONS = {
    "N009": ("EXISTING_GAP", "Repeated-state probe returns 0 twice on all three sides; uninitialized DRBG lifecycle gap already exists at S0+H0 and is not shown to be aggravated."),
    "N012": ("MECHANICAL_COMPATIBILITY", "Old HAS and new MD_CAN feature macros coexist under identical conditions; no independently verified silent inadequacy."),
    "N019": ("MECHANICAL_COMPATIBILITY", "Macro-guard migration is mechanically equivalent at the commit; no independently verified silent inadequacy."),
}


def read_csv(path: Path) -> list[dict[str, str]]:
    csv.field_size_limit(sys.maxsize)
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]], fields: list[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows and fields is None:
        raise ValueError(f"no rows for {path}")
    fields = fields or list(rows[0])
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git(repo: Path, *args: str) -> str:
    result = subprocess.run(["git", "-C", str(repo), *args], text=True,
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        raise RuntimeError(result.stderr)
    return result.stdout


def aggregate(rows: list[dict[str, str]], id_key: str) -> dict[tuple[str, str], tuple[str, str, str]]:
    groups: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[(row[id_key], row["side"])].append(row)
    result = {}
    for key, values in groups.items():
        builds = [r["build"] for r in values]
        runtimes = [r["runtime"] for r in values]
        build = "PASS" if builds and all(x == "PASS" for x in builds) else "FAIL" if "FAIL" in builds else builds[0]
        runtime = "PASS" if runtimes and all(x == "PASS" for x in runtimes) else "FAIL" if "FAIL" in runtimes else "NOT_RUN"
        detail = "; ".join(f"{r.get('harness_file') or r.get('target','')}={r['build']}/{r['runtime']}" for r in values)
        result[key] = (build, runtime, detail)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    manifest_path = FROZEN / "audit_manifest.json"
    if manifest_path.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite existing ground-truth freeze: {manifest_path}")

    candidates = {row["candidate_id"]: row for row in read_csv(DATA / "new_candidates.csv")}
    controls = {row["control_id"]: row for row in read_csv(DATA / "source_only_negative_controls.csv")}

    internal_ids = list(SILENT) + EXPLICIT + list(COEV_NEG) + list(controls)
    assert len(internal_ids) == 80 and len(set(internal_ids)) == 80
    shuffled = internal_ids[:]
    random.Random(SEED).shuffle(shuffled)
    case_for = {internal: f"C{index:03d}" for index, internal in enumerate(shuffled, 1)}

    # Preserve complete source and harness diffs as pre-freeze evidence.
    diff_dir = RAW / "audited-diffs"
    diff_dir.mkdir(parents=True, exist_ok=True)
    all_items: dict[str, dict[str, str]] = {**candidates, **controls}
    for internal in internal_ids:
        item = all_items[internal]
        repo = PROJECT_ROOT / item["project"]
        source_paths = json.loads(item["source_files_changed"])
        harness_paths = json.loads(item.get("harness_files_changed", "[]"))
        source_diff = git(repo, "diff", "--no-ext-diff", "--no-renames", "--full-index",
                          item["parent"], item["commit"], "--", *source_paths)
        harness_diff = git(repo, "diff", "--no-ext-diff", "--no-renames", "--full-index",
                           item["parent"], item["commit"], "--", *harness_paths) if harness_paths else ""
        (diff_dir / f"{internal}.source.patch").write_text(source_diff, encoding="utf-8")
        (diff_dir / f"{internal}.harness.patch").write_text(harness_diff, encoding="utf-8")

    wuffs_agg = aggregate(read_csv(GROUND / "wuffs_all_probe_details.csv"), "candidate_id")
    portfolio_agg = aggregate(read_csv(GROUND / "wuffs_new_target_portfolio_probe_details.csv"), "candidate_id")
    wuffs_agg.update(portfolio_agg)
    mbed_agg = aggregate(read_csv(GROUND / "mbedtls_all_probe_details.csv"), "candidate_id")
    control_agg = aggregate(read_csv(GROUND / "source_only_control_probe_details.csv"), "control_id")
    solidity_sources = [
        GROUND / "solidity_version_probe_details.csv",
        GROUND / "solidity_reset_state_probe_details.csv",
        GROUND / "solidity_optimizer_modes_probe_details.csv",
    ]
    solidity_agg = aggregate([row for path in solidity_sources for row in read_csv(path)], "candidate_id")

    coverage_by_id = {row["candidate_id"]: row for row in read_csv(GROUND / "wuffs_changed_code_coverage.csv")}
    coverage_by_id["N128"] = {
        "changed_lines": "8", "changed_functions": '["OptimiserSettings::removeInvalidCharacters"]',
        "h0_changed_lines_covered": "0", "h1_changed_lines_covered": "8",
        "h0_changed_coverage": "0.000000", "h1_changed_coverage": "1.000000",
        "delta_changed_coverage": "1.000000", "h0_instrumented_build": "PASS",
        "h1_instrumented_build": "PASS",
        "measurement_scope": "S1 executable lines in real OptimiserSettings.h helper; GCC 13 gcov component probe",
    }

    def kind(internal: str) -> tuple[str, str, str, str]:
        if internal in SILENT:
            return "VERIFIED_SILENT_POSITIVE", SILENT[internal][0], "", SILENT[internal][2]
        if internal in EXPLICIT:
            return "VERIFIED_EXPLICIT_POSITIVE", "VP1", "", "S1+H0 fails to build while S0+H0 and S1+H1 pass."
        if internal in COEV_NEG:
            ntype, rationale = COEV_NEG[internal]
            return "VERIFIED_NEGATIVE", "", ntype, rationale
        control = controls[internal]
        return "VERIFIED_NEGATIVE", "", control["negative_type"], control["audit_rationale"]

    def item_for(internal: str) -> dict[str, str]:
        return all_items[internal]

    def agg_for(internal: str) -> dict[tuple[str, str], tuple[str, str, str]]:
        project = item_for(internal)["project"]
        if internal.startswith("S"):
            return control_agg
        if project == "wuffs":
            return wuffs_agg
        if project == "mbedtls":
            return mbed_agg
        if project == "solidity":
            return solidity_agg
        raise KeyError(project)

    build_rows = []
    coverage_rows = []
    reach_rows = []
    state_rows = []
    label_rows = []
    audit_rows = []

    reach_map = {
        "N185": ("io_buffer reader/writer", "NOT_REACHED", "REACHED"),
        "N202": ("image_config.work_buffer_size", "NOT_REACHED", "REACHED"),
        "N206": ("malloc_slice_u8", "NOT_REACHED", "REACHED"),
        "N207": ("gif.decoder.workbuf_len", "LIMITED", "REACHED"),
        "N215": ("frame_dirty_rect invariant oracle", "NOT_OBSERVED", "OBSERVED"),
        "N216": ("short-read dirty-rect invariant oracle", "NOT_OBSERVED", "OBSERVED"),
        "N223": ("JSON decoder fuzz entry", "NOT_REACHABLE_FROM_H0_PORTFOLIO", "REACHABLE"),
        "N228": ("extended-token signed value domain", "PARTIAL_NONNEGATIVE_ONLY", "REACHED_SIGNED_DOMAIN"),
        "N231": ("CBOR decoder fuzz entry", "NOT_REACHABLE_FROM_H0_PORTFOLIO", "REACHABLE"),
        "N233": ("trailing-comment decoder paths", "LIMITED", "IMPROVED"),
        "N234": ("valid trailing-comment/newline configuration", "NOT_CONFIGURABLE", "CONFIGURABLE"),
        "N237": ("u64.rotate_right", "NOT_REACHED", "REACHED"),
        "N244": ("YA_NONPREMUL swizzle paths", "NOT_REACHED", "REACHED"),
        "N248": ("Y_16LE swizzle paths", "NOT_REACHED", "REACHED"),
        "N249": ("BGRA_PREMUL_4X16LE swizzle paths", "NOT_REACHED", "REACHED"),
        "N250": ("0x80 ycc-model semantic branch", "NOT_REACHED", "REACHED"),
        "N071": ("YulStringRepository::reset", "NOT_REACHED_PER_ITERATION", "REACHED_PER_ITERATION"),
        "N116": ("Paris configuration", "NOT_SELECTABLE", "SELECTABLE"),
        "N128": ("OptimiserSettings::removeInvalidCharacters", "NOT_REACHED", "REACHED"),
        "N132": ("Prague configuration", "NOT_SELECTABLE", "SELECTABLE"),
    }

    for internal in shuffled:
        case_id = case_for[internal]
        item = item_for(internal)
        label, ptype, ntype, rationale = kind(internal)
        agg = agg_for(internal)
        statuses = {}
        details = {}
        for side in ("S0_H0", "S1_H0", "S1_H1"):
            statuses[side] = agg[(internal, side)][:2]
            details[side] = agg[(internal, side)][2]
        build_rows.append({
            "case_id": case_id, "internal_id": internal, "project": item["project"],
            "s0_h0_build": statuses["S0_H0"][0], "s0_h0_runtime": statuses["S0_H0"][1],
            "s1_h0_build": statuses["S1_H0"][0], "s1_h0_runtime": statuses["S1_H0"][1],
            "s1_h1_build": statuses["S1_H1"][0], "s1_h1_runtime": statuses["S1_H1"][1],
            "classification_hint": label, "validation_scope": "component" if item["project"] == "solidity" else "native historical target",
            "detail": " | ".join(f"{s}: {details[s]}" for s in ("S0_H0", "S1_H0", "S1_H1")),
        })

        cov = coverage_by_id.get(internal)
        if cov is None:
            cov = {key: "NOT_MEASURED" for key in (
                "changed_lines", "changed_functions", "h0_changed_lines_covered", "h1_changed_lines_covered",
                "h0_changed_coverage", "h1_changed_coverage", "delta_changed_coverage",
                "h0_instrumented_build", "h1_instrumented_build", "measurement_scope")}
            cov["measurement_scope"] = "NOT_MEASURED; no reliable changed-line instrumentation in the audited build"
        coverage_rows.append({"case_id": case_id, "internal_id": internal, **cov})

        if internal in reach_map:
            target, h0reach, h1reach = reach_map[internal]
            reach_evidence = SILENT[internal][5]
        else:
            target = h0reach = h1reach = "NOT_MEASURED"
            reach_evidence = "NOT_MEASURED; label does not rely on a reachability claim"
        reach_rows.append({
            "case_id": case_id, "internal_id": internal, "target_function_or_entry": target,
            "s1_h0_reachability": h0reach, "s1_h1_reachability": h1reach,
            "evidence": reach_evidence,
        })

        if internal in SILENT:
            spec = SILENT[internal]
            state_rows.append({
                "case_id": case_id, "internal_id": internal, "requirement": spec[2],
                "s0_h0": "requirement absent or pre-change baseline retained",
                "s1_h0": spec[3], "s1_h1": spec[4], "evidence": spec[5],
                "source_patch": f"raw-evidence/audited-diffs/{internal}.source.patch",
                "harness_patch": f"raw-evidence/audited-diffs/{internal}.harness.patch",
            })

        harness_id = SILENT[internal][1] if internal in SILENT else (
            controls[internal]["harness_file"] if internal in controls else json.loads(item["harness_files_changed"])[0]
        )
        evidence_type = (
            "dynamic_coverage_and_code" if internal in coverage_by_id and internal in SILENT
            else "dynamic_component_and_code" if internal in SILENT
            else "three_way_build_runtime" if internal in EXPLICIT
            else "three_way_build_runtime_and_code_audit"
        )
        label_rows.append({
            "case_id": case_id, "internal_id": internal, "project": item["project"],
            "commit": item["commit"], "parent": item["parent"], "timestamp": item["timestamp"],
            "harness_id": harness_id, "label": label, "positive_type": ptype,
            "negative_type": ntype, "build_h0": statuses["S1_H0"][0], "runtime_h0": statuses["S1_H0"][1],
            "changed_coverage_h0": cov["h0_changed_coverage"], "changed_coverage_h1": cov["h1_changed_coverage"],
            "reachability_h0": h0reach, "reachability_h1": h1reach,
            "evidence_type": evidence_type, "evidence_summary": rationale if internal not in SILENT else SILENT[internal][5],
            "audit_status": "FROZEN_VALID",
        })
        audit_rows.append({
            "case_id": case_id, "internal_id": internal, "project": item["project"],
            "commit": item["commit"], "parent": item["parent"], "timestamp": item["timestamp"],
            "selection_status": "INCLUDED", "label": label, "positive_type": ptype,
            "negative_type": ntype, "audit_rationale": rationale,
            "s0_h0": "/".join(statuses["S0_H0"]), "s1_h0": "/".join(statuses["S1_H0"]),
            "s1_h1": "/".join(statuses["S1_H1"]), "evidence_source": f"ground-truth/build_runtime_validation.csv; raw-evidence/audited-diffs/{internal}.*.patch",
        })

    # Record every mined but unselected co-evolution candidate without claiming
    # a full build audit for cases that were screened out pre-freeze.
    excluded_rows = []
    for internal, item in candidates.items():
        if internal in internal_ids:
            continue
        status, reason = KNOWN_EXCLUSIONS.get(internal, (
            "NOT_SELECTED_PRE_FREEZE",
            "Screened out before freeze: not needed for the fixed strata or lacked sufficiently objective counterfactual evidence within the available historical build environment.",
        ))
        row = {
            "internal_id": internal, "project": item["project"], "commit": item["commit"],
            "parent": item["parent"], "timestamp": item["timestamp"], "exclusion_status": status,
            "reason": reason, "prediction_seen": "NO",
        }
        excluded_rows.append(row)
        audit_rows.append({
            "case_id": "", "internal_id": internal, "project": item["project"], "commit": item["commit"],
            "parent": item["parent"], "timestamp": item["timestamp"], "selection_status": status,
            "label": "NOT_IN_DATASET", "positive_type": "", "negative_type": "",
            "audit_rationale": reason, "s0_h0": "NOT_AUDITED_FOR_FINAL_SET",
            "s1_h0": "NOT_AUDITED_FOR_FINAL_SET", "s1_h1": "NOT_AUDITED_FOR_FINAL_SET",
            "evidence_source": "data/new_candidates.csv",
        })
    excluded_rows.append({
        "internal_id": "SOURCE_CONTROL_REPLACED", "project": "wuffs",
        "commit": "f569a505a6a8041ae63b522513728a8d3d505b81", "parent": "",
        "timestamp": "", "exclusion_status": "INFRASTRUCTURE_INCOMPATIBILITY",
        "reason": "Initial S022 control failed all three builds due to a pre-existing unrelated API inconsistency; replaced before ground-truth freeze.",
        "prediction_seen": "NO",
    })

    write_csv(DATA / "candidate_audit.csv", sorted(audit_rows, key=lambda r: (r["selection_status"] != "INCLUDED", r["project"], r["timestamp"], r["internal_id"])))
    write_csv(DATA / "excluded_cases.csv", excluded_rows)
    write_csv(GROUND / "build_runtime_validation.csv", sorted(build_rows, key=lambda r: r["case_id"]))
    write_csv(GROUND / "changed_code_coverage.csv", sorted(coverage_rows, key=lambda r: r["case_id"]))
    write_csv(GROUND / "reachability_validation.csv", sorted(reach_rows, key=lambda r: r["case_id"]))
    write_csv(GROUND / "state_config_validation.csv", sorted(state_rows, key=lambda r: r["case_id"]))

    FROZEN.mkdir(parents=True, exist_ok=True)
    label_rows.sort(key=lambda r: r["case_id"])
    write_csv(FROZEN / "labels.csv", label_rows)
    write_csv(FROZEN / "silent_positive.csv", [r for r in label_rows if r["label"] == "VERIFIED_SILENT_POSITIVE"])
    write_csv(FROZEN / "explicit_positive.csv", [r for r in label_rows if r["label"] == "VERIFIED_EXPLICIT_POSITIVE"])
    write_csv(FROZEN / "negative.csv", [r for r in label_rows if r["label"] == "VERIFIED_NEGATIVE"])

    counts = Counter(r["label"] for r in label_rows)
    taxonomy = Counter(r["positive_type"] for r in label_rows if r["positive_type"])
    projects = Counter(r["project"] for r in label_rows)
    canonical = json.dumps(label_rows, sort_keys=True, separators=(",", ":")).encode()
    dataset_hash = hashlib.sha256(canonical).hexdigest()
    frozen_at = datetime.now(timezone.utc).isoformat()
    frozen_files = [FROZEN / name for name in ("labels.csv", "silent_positive.csv", "explicit_positive.csv", "negative.csv")]
    manifest = {
        "ground_truth_frozen_at": frozen_at,
        "dataset_hash": dataset_hash,
        "case_assignment_seed": SEED,
        "dataset_size": len(label_rows),
        "counts": dict(counts),
        "positive_taxonomy": dict(taxonomy),
        "project_distribution": dict(projects),
        "source_candidate_count": len(candidates),
        "source_only_control_count": len(controls),
        "prediction_completed_before_freeze": False,
        "relabel_policy": "Never relabel after freeze; any serious error becomes INVALID and is separately recorded.",
        "files": {path.relative_to(ROOT).as_posix(): sha256(path) for path in frozen_files},
        "validation_evidence": {
            path.relative_to(ROOT).as_posix(): sha256(path)
            for path in [
                GROUND / "build_runtime_validation.csv", GROUND / "changed_code_coverage.csv",
                GROUND / "reachability_validation.csv", GROUND / "state_config_validation.csv",
                GROUND / "wuffs_all_probe_details.csv", GROUND / "mbedtls_all_probe_details.csv",
                GROUND / "source_only_control_probe_details.csv", *solidity_sources,
                GROUND / "wuffs_new_target_portfolio_probe_details.csv",
            ]
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
